export const fakePromotionTypes = {
  data: {
    promotionTypes: [
      {
        name: 'freeStock',
        displayName: 'Free Stock',
        description: '',
        __typename: 'PromotionType',
      },
      { name: 'moneyOff', displayName: 'Money Off', description: '', __typename: 'PromotionType' },
    ],
  },
}.data.promotionTypes;
export const fakePromotion = {
  pageProps: {
    promotions: [
      {
        id: 35,
        type: {
          name: 'freeStock',
          displayName: 'Free Stock',
          description: '',
          __typename: 'PromotionType',
        },
        name: 'Buy 3 Stella get 1 Free',
        slug: 'buy-3-stella-get-1-free',
        shortDescription: 'Buy 3 cases of Stella bottles and get one on us.',
        longDescription:
          'The good people at ABInbev have gven us an incredible deal which we can pass on to you - buy 3 cases of Stella 330ml bottles and get a 4th case on us. Limited to 10 free cases per customer that is a possible 240 bottles for Free!',
        imagePath: 'stella.png',
        priority: 0,
        status: 'active',
        identityCode: '003',
        terms: '',
        activeFrom: '2020-11-12T15:47:18Z',
        activeTo: null,
        productsInPromotion: [666723],
        __typename: 'Promotion',
      },
      {
        id: 43,
        type: {
          name: 'moneyOff',
          displayName: 'Money Off',
          description: '',
          __typename: 'PromotionType',
        },
        name: 'Buy any 2 cases of Smirnoff flavoured and get £10 discount',
        slug: 'buy-any-2-cases-of-smirnoff-flavoured-and-get-10-discount',
        shortDescription:
          'For every 2 cases of Smirnoff Flavoured Vodka you buy we will discount the price by £10',
        longDescription:
          'How do we do it? You wanted bigger discount and we deliver - £10 off every 2 cases of Smirnoff flavoured vodka with NO LIMITS. (Applies to cases of 6 only - not individual bottles)',
        imagePath: 'smirnoff.png',
        priority: 0,
        status: 'active',
        identityCode: '012',
        terms: '',
        activeFrom: '2020-11-12T15:47:18Z',
        activeTo: null,
        productsInPromotion: [3055, 3047, 3046],
        __typename: 'Promotion',
      },
      {
        id: 33,
        type: {
          name: 'freeStock',
          displayName: 'Free Stock',
          description: '',
          __typename: 'PromotionType',
        },
        name: 'Buy one Get one Free on English Wine',
        slug: 'buy-one-get-one-free-on-englsh-wine',
        shortDescription: 'BOGOF on the Chapel Down Product range',
        longDescription:
          'An amazing opportunity to sample the finest British Wines.  We have teamed up with the Chapel Down team to bring you an incredible offer - Buy one get one free for each wine you purchase between now and December.  This promotion is limited to 12 deals per customer.',
        imagePath: 'chapel-down.png',
        priority: 0,
        status: 'active',
        identityCode: '001',
        terms: '',
        activeFrom: '2020-11-12T15:47:18Z',
        activeTo: null,
        productsInPromotion: [
          666919,
          666914,
          666915,
          666916,
          666917,
          666918,
          666911,
          666912,
          666913,
        ],
        __typename: 'Promotion',
      },
      {
        id: 37,
        type: {
          name: 'freeStock',
          displayName: 'Free Stock',
          description: '',
          __typename: 'PromotionType',
        },
        name: 'Coca-Cola give you Zero',
        slug: 'coca-cola-give-you-zero',
        shortDescription:
          'Buy 3 cases of Glass bottles from the Icon range and get a free Coke Zero.',
        longDescription:
          'The only time that getting Zero is best for you.  Coca-cola want to give you a free case of Coke Zero Glass bottles when you buy 3 from the range. Limited to 10 free cases per customer.',
        imagePath: 'coca-cola-zero.png',
        priority: 0,
        status: 'active',
        identityCode: '005',
        terms: '',
        activeFrom: '2020-11-12T15:47:18Z',
        activeTo: null,
        productsInPromotion: [666702, 666712, 666683, 666684],
        __typename: 'Promotion',
      },
      {
        id: 36,
        type: {
          name: 'freeStock',
          displayName: 'Free Stock',
          description: '',
          __typename: 'PromotionType',
        },
        name: 'Free Rekorderlig Spiced Plum',
        slug: 'free-rekorderlig-spiced-plum',
        shortDescription:
          'Buy 3 cases of Rekorderlig bottles and sample the new Spiced Plum flavour on us',
        longDescription:
          'Rekorderlig have exclusively offered us the chance to try their Spiced Plum flavour when you buy from our range. Buy and 3 cases of Rekorderlig bottles to receive your free case.  (Limited to 2 free cases per customer.)',
        imagePath: 'rekorderlig.png',
        priority: 0,
        status: 'active',
        identityCode: '004',
        terms: '',
        activeFrom: '2020-11-12T15:47:18Z',
        activeTo: null,
        productsInPromotion: [2961, 2960, 2959, 2958],
        __typename: 'Promotion',
      },
      {
        id: 42,
        type: {
          name: 'freeStock',
          displayName: 'Free Stock',
          description: '',
          __typename: 'PromotionType',
        },
        name: 'Free Schweppes Tonic when you buy 6',
        slug: 'free-schweppes-tonic-when-you-buy-6',
        shortDescription: 'Buy any 6 cases from the Schweppes 200ml range and get a Tonic on us.',
        longDescription:
          'Buy 6 cases from our 200ml range and get a free case of Schweppes Tonic. Limited to 4 deals per order.',
        imagePath: 'schweppes.png',
        priority: 0,
        status: 'active',
        identityCode: '010',
        terms: '',
        activeFrom: '2020-11-12T15:47:18Z',
        activeTo: null,
        productsInPromotion: [666934, 666688, 666692, 666690, 666691, 666689, 666936],
        __typename: 'Promotion',
      },
      {
        id: 40,
        type: {
          name: 'freeStock',
          displayName: 'Free Stock',
          description: '',
          __typename: 'PromotionType',
        },
        name: 'Lockdown pregnancy support package',
        slug: 'lockdown-pregnancy-support-package',
        shortDescription: 'Buy 2 appletiser and get 1 free',
        longDescription:
          'Supporting the lockdown pregancy cause - offer Applestiser to those who need it. Buy any 2 cases of 24 Appletiser and get 1 free. Limited to 3 free cases per order.',
        imagePath: 'appletiser.png',
        priority: 0,
        status: 'active',
        identityCode: '008',
        terms: '',
        activeFrom: '2020-11-12T15:47:18Z',
        activeTo: null,
        productsInPromotion: [666920],
        __typename: 'Promotion',
      },
      {
        id: 38,
        type: {
          name: 'freeStock',
          displayName: 'Free Stock',
          description: '',
          __typename: 'PromotionType',
        },
        name: 'Modelo - Buy 4 get 1 free',
        slug: 'modelo-buy-4-get-1-free',
        shortDescription: 'Buy 4 cases of Model and we will send you a 5th for free.',
        longDescription:
          'Discover the refreshing taste of Mexico with our Modelo offer. Buy 4 cases and we will send you a 5th for Free. Limited to 5 free cases per customer.',
        imagePath: 'modelo.png',
        priority: 0,
        status: 'active',
        identityCode: '006',
        terms: '',
        activeFrom: '2020-11-12T15:47:18Z',
        activeTo: null,
        productsInPromotion: [666722],
        __typename: 'Promotion',
      },
      {
        id: 39,
        type: {
          name: 'freeStock',
          displayName: 'Free Stock',
          description: '',
          __typename: 'PromotionType',
        },
        name: 'Punked out - get Drowned in Elvis Juice',
        slug: 'punked-out-get-drowned-in-elvis-juice',
        shortDescription: 'Buy any 8 cases from the range and we will drown you in Elvis Juice.',
        longDescription:
          'Buy any 8 cases from our range and receive 2 cases of Elvis Juice on us; this offer is limited to 1 deal per customer. Use it wisely.',
        imagePath: 'elvis.png',
        priority: 0,
        status: 'active',
        identityCode: '007',
        terms: '',
        activeFrom: '2020-11-12T15:47:18Z',
        activeTo: null,
        productsInPromotion: [666879, 666877, 666878, 666882, 666885],
        __typename: 'Promotion',
      },
      {
        id: 34,
        type: {
          name: 'freeStock',
          displayName: 'Free Stock',
          description: '',
          __typename: 'PromotionType',
        },
        name: 'Thatchers - Free Case',
        slug: 'thatchers-free-case',
        shortDescription:
          'Buy 5 from the Thatchers bottle range and get a free case of Thatchers Gold 12x500ml',
        longDescription:
          'Cider is so popular right now and Thatchers make some of the best.  Buy any 5 cases from the range and get a free case of Thatchers Gold.  Limited to 20 free cases per customer.',
        imagePath: 'thatchers.png',
        priority: 0,
        status: 'active',
        identityCode: '002',
        terms: '',
        activeFrom: '2020-11-12T15:47:18Z',
        activeTo: null,
        productsInPromotion: [666906, 666905, 666903, 666902, 666901],
        __typename: 'Promotion',
      },
      {
        id: 41,
        type: {
          name: 'moneyOff',
          displayName: 'Money Off',
          description: '',
          __typename: 'PromotionType',
        },
        name: '£5 off Coca-cola postmix when you buy 3 or more',
        slug: '5-off-coca-cola-postmix-when-you-buy-3-or-more',
        shortDescription: 'Get £5 off each Postmix box when you buy 3 or more from the range',
        longDescription:
          'Buy any 3 (or more) 7ltr Postmix from the range and receive a whopping £5 off each on top of the incredible price we already have.',
        imagePath: 'coca-cola-1.png',
        priority: 0,
        status: 'active',
        identityCode: '009',
        terms: '',
        activeFrom: '2020-11-12T15:47:18Z',
        activeTo: null,
        productsInPromotion: [666705, 666704, 666706, 666709],
        __typename: 'Promotion',
      },
    ],
  },
  __N_SSG: true,
}.pageProps.promotions;
